<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Equilibrium index') ?></h3>
            </div>
            <div class="panel-body">
                <p><pre><?php print_r($this->equilibrium)?></pre></p>
                <p><a class="btn btn-success pull-right" href="<?=$this->url('equilibrium', ['values' => '2,1,7,3a', 'mode' => 'strict'])?>"><?php echo $this->translate('Go to equilibrium strict') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
