checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths: [Equilibrium/*]
    excluded_paths: [config/*, language/*]
tools:
    external_code_coverage:
        timeout: 1000
