language: php
php:
    - 5.5
before_script:
    - composer self-update
    - composer --dev install
script:
  - phpunit -c module/Equilibrium/test/phpunit.xml
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
